"""empty message

Revision ID: 2221d11de1b
Revises: None
Create Date: 2015-08-06 16:13:50.834748

"""

# revision identifiers, used by Alembic.
revision = '2221d11de1b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('chunk',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.translation_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_table('translation')
    ### end Alembic commands ###
